### ISSUE TITLE
why i type dtf -h ,can not work

### ISSUE THREAD

**Issue by mathoyus** [jakev/dtf#33]
root@ubuntu:/etc/ssh/dtf# ./setup.py
dtf installation started...
Completion output is already generated, skipping
dtf_core.sh output is already generated, skipping
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

root@ubuntu:/etc/bash_completion.d# dtf -h
No command 'dtf' found, did you mean:
 Command 'dt' from package 'ditrack' (universe)
 Command 'dtc' from package 'device-tree-compiler' (main)
 Command 'tf' from package 'tf' (universe)
 Command 'tf' from package 'tf5' (universe)
 Command 'wtf' from package 'bsdgames' (universe)
 Command 'dff' from package 'dff' (universe)
 Command 'gtf' from package 'xserver-xorg-core' (main)

**Comment by jakev** [comment]
Thanks for your interest in the tool! The installation failed based on the output you included. Please run the command exactly as the README.md states:

```
sudo python setup.py install
```

After that, try to run `dtf -h` again
