### ISSUE TITLE
dtfmods-core-v1.2.0.zip cannot download

### ISSUE THREAD

**Issue by mathoyus** [jakev/dtf#34]
root@ubuntu:/etc/ssh/dtf# wget https://www.thecobraden.com/uploads/dtfmods-core-v1.2.0.zip
--2016-05-11 08:18:39--  https://www.thecobraden.com/uploads/dtfmods-core-v1.2.0.zip
Resolving www.thecobraden.com (www.thecobraden.com)... 167.114.3.81
Connecting to www.thecobraden.com (www.thecobraden.com)|167.114.3.81|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-05-11 08:18:59 ERROR 404: Not Found.

**Comment by jakev** [comment]
Closed, as this is a issue with the dtfmods, and not the framework: https://github.com/jakev/dtfmods-core/issues/66
